### ISSUE TITLE
In python 3.5 there is no .next() (Or something like that.)

### ISSUE THREAD

**Issue by sovietnorm** [Alonreznik/dynamodb-json#6]
In json_util.py, line 43 and 45 use the next() keyword instead of generator.next() for great good like so;

`    if as_dict:
        return next(six.iteritems(result_))[1]
    else:
        return json.dumps(next(six.iteritems(result_))[1], **kwargs)`

Or else;

`json.dumps({'foo': 'bar'}, True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "python3.5/site-packages/dynamodb_json/json_util.py", line 43, in dumps
    return six.iteritems(result_).next()[1]
AttributeError: 'dict_itemiterator' object has no attribute 'next'`

PS: Sorry I didn't just make a patch. Too lazy.

**Comment by JLee21** [comment]
PR requested for this issue.

**Comment by Alonreznik** [comment]
Hi.
Thank you for your issue and thank you @JLee21 for your PR. I've uploaded new version into master and make a release in the next days after some more checking. 
@JLee21 - Please be noticed that your PR had some issues in json_utils.py, so i took your PR, fixed your code and deployed it. 

Please check it on your py3.5 if you can.

Thank you

Alon

**Comment by JLee21** [comment]
Thanks @Alonreznik 
I pulled and installed the latest and I have it working on Python 3.6.2
@sovietnorm was using Python 3.5 originally.

**Comment by dan-hook** [comment]
Any idea when you'll release the fixed version to pypi?

**Comment by MrTeale** [comment]
I second @dan-hook on this.

**Comment by Alonreznik** [comment]
Hi! 
@sovietnorm @JLee21 @dan-hook 
@MrTeale  @ransford
 
So sorry for the huge delay.
New release (1.3) had been deployed.

Hope you find it well.

Alon

**Comment by MrTeale** [comment]
Legend @Alonreznik Thank you so much
